### ISSUE TITLE
fatal error u1077

### ISSUE THREAD

**Issue by trivedidivya** [akshay-c/LDmicro#2]
everytime i try running make.bat file .
fatal error u1077 with return code 0x2 or 0xffffffff comes. although i have installed both the perl and GNU utilities.
GNU utilities have been placed in ldmicro folder .
![screenshot 232](https://user-images.githubusercontent.com/30649856/37613003-de3ea132-2bcc-11e8-8580-098628601f05.png)

**Comment by akshay-c** [comment]
1. You need not place GNU utilities in ldmicro folder.
You can set the path to the folder in 'path' environment variable permanently. Visit link to know how
https://www.java.com/en/download/help/path.xml

2. I strongly feel you have deleted the 'sample' folder before running make command

**Comment by akshay-c** [comment]
Kindly fork the repository before contributing.

**Comment by trivedidivya** [comment]
none of the solutions helped.
i did not delete the sample folder and set the path variable but still getting the same issue

**Comment by akshay-c** [comment]
Have you made any changes to the source code? Seems you have changed original source code of ldmicro which is responsible for hex file generation.

**Comment by trivedidivya** [comment]
no not yet

**Comment by akshay-c** [comment]
It does not look like you are compiling from visual studio command prompt. Are you?

**Comment by trivedidivya** [comment]
i am compiling from visual studio 10.0 prompt only . i have again downloaded the zip file and tried executing the make.bat file.
 the following error came
![screenshot 233](https://user-images.githubusercontent.com/30649856/37696482-c391ae70-2cfc-11e8-9c1b-c0103ce7264c.png)

**Comment by trivedidivya** [comment]
![screenshot 234](https://user-images.githubusercontent.com/30649856/37696505-04a686d8-2cfd-11e8-87f2-f10182fb742a.png)

**Comment by trivedidivya** [comment]
can you list down the steps exactly . As in where to place all the files required.

**Comment by akshay-c** [comment]
File downloaded from github can be anywhere on your machine.
Visual studio command prompt is a utility which you will find under 'Microsoft Visual Studio Express Edition' folder inside 'Programs' menu.
After opening the visual studio command prompt, browse to ldmicro folder inside the folder downloaded from github.
Simply execute 'make' to compile, 'make clean' to remove all dependencies during make.

Kindly read the mails in your inbox and visit OpenPLC fellowship page again for submission procedure. 
Seems you have not yet logged into the submission interface.

**Comment by akshay-c** [comment]
this is not visual studio command prompt.
![vscommand](https://user-images.githubusercontent.com/8157223/37704073-ab2284f2-2cef-11e8-85b2-7af8cfae5aec.jpg)

This is what visual studio command prompt looks like.

**Comment by akshay-c** [comment]
Hi,
   I tried compiling the source code on a windows10 machine, your problem exists on the machine.

The compilation still succeeds, the error thrown is somethings that needs to be handled. Kindly ignore this particular error, since the error is thrown after compilation. Ignore the hex differences for now. You can still find the ldmicro.exe executable listed in the folder. You may start executing it for the moment.

**Comment by akshay-c** [comment]
replace the contents of 'ldmicro/expected' folder with attached files
[expected.zip](https://github.com/akshay-c/LDmicro/files/1833125/expected.zip)

**Comment by trivedidivya** [comment]
there is no folder by the name expected folder

**Comment by akshay-c** [comment]
Sorry my mistake. The folder is inside 'ldmicro/reg' directory.
This is not a valid issue since you are not following the steps.  You are not supposed to download the zip file of the project, but clone it with 'git clone <repository>' command. for more info see github documentation or tutorials.
